name: Algolia docsearch scraper

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run the docsearch scraper
      run: |
        docker run --env APPLICATION_ID=${{ secrets.APPLICATION_ID }} --env API_KEY=${{ secrets.API_KEY }} --env CONFIG='${{ secrets.CONFIG }}' algolia/docsearch-scraper
